# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170513_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_link',
            new_name='song_file',
        ),
    ]
